Repository fga-eps-mds/2019.2-Git-Breakdown, pull requests merged in 2019-09, with the labels that each got.

#36 Feat#29/GitHub api commits request
  .gitignore
  APIs/commit_request/api/commits/get_all_commits.js
  APIs/commit_request/readme.md
  APIs/commit_request/routes/routes.js
  APIs/commit_request/server/server.js
Labels: Funcionalidade, MDS

#32 Feat#31/fetch issue informations
  APIs/issues_request/.gitignore
  APIs/issues_request/bin/server.js
  APIs/issues_request/package.json
  APIs/issues_request/src/app.js
  APIs/issues_request/src/controllers/issueController.js
  APIs/issues_request/src/routes/index.js
  APIs/issues_request/src/routes/issueRoute.js
  APIs/issues_request/test/issueRoute.js
Labels: Funcionalidade, MDS

#37 Feat#24/pullrequest microservices
  .gitignore
  APIs/pullrequests_request/.dockerignore
  APIs/pullrequests_request/.gitignore
  APIs/pullrequests_request/Dockerfile
  APIs/pullrequests_request/bin/server.js
  APIs/pullrequests_request/package.json
  APIs/pullrequests_request/src/app.js
  APIs/pullrequests_request/src/controllers/pullrequestController.js
  APIs/pullrequests_request/src/routes/index.js
  APIs/pullrequests_request/src/routes/pullrequestRoute.js
  APIs/pullrequests_request/test/pullrequestRoute.js
  docker-compose.yml
Labels: Funcionalidade, MDS

#40 Feat#33/api gateway
  APIs/api_gateway/.dockerignore
  APIs/api_gateway/.gitignore
  APIs/api_gateway/Dockerfile
  APIs/api_gateway/package.json
  APIs/api_gateway/src/index.js
  APIs/commit_request/api/commits/get_all_commits.js
  docker-compose.yml
Labels: Funcionalidade, MDS, WIP

#35 Feat#26/redirect to login
  extension/manifest.json
  extension/popup.html
  extension/scripts/background.js
  extension/scripts/constants.js
  extension/scripts/oauth.js
  extension/scripts/popup.js
Labels: Funcionalidade, MDS

#44 Feat#22/filter issues information
  APIs/api_gateway/src/index.js
  APIs/issues_request/.gitignore
  APIs/issues_request/src/controllers/issueController.js
  APIs/issues_request/test/issueRoute.js
Labels: Funcionalidade, MDS

#56 feat(#53): creating logout confirmation
  extension/scripts/popup.js
Labels: MDS, aprimoramento

#55 Feat#21/filter commits information
  APIs/commit_request/Dockerfile
  APIs/commit_request/api/commits/get_all_commits.js
  APIs/commit_request/readme.md
  APIs/commits_request/.dockerignore
  APIs/commits_request/.gitignore
  APIs/commits_request/Dockerfile
  APIs/commits_request/controllers/commitController.js
  APIs/commits_request/package.json
  APIs/commits_request/routes/commitsRoute.js
  APIs/commits_request/server/server.js
  APIs/commits_request/test/commitsRoute.js
  docker-compose.yml
Labels: Funcionalidade, MDS

#59 Feat#41/refactor vision document
  mkdocs/docs/documento_visao.md
Labels: aprimoramento, documentação

#57 Feat#47/create issues chart
  .gitignore
  extension/manifest.json
  extension/popup.html
  extension/scripts/graph.js
  extension/scripts/popup.js
Labels: Funcionalidade, MDS

#68 Feat#42/refactor architecture document
  mkdocs/docs/documento_arquitetura.md
Labels: aprimoramento, documentação

#54 Feat#52/integration tests
  APIs/api_gateway/package.json
  APIs/api_gateway/src/index.js
  APIs/api_gateway/test/index.js
  APIs/branches_request/src/controllers/branchController.js
Labels: Automação, MDS, aprimoramento, teste
