Repository fga-eps-mds/2019.2-Git-Breakdown, pull requests merged in 2019-11, with the labels that each got.

#105 Feat#100/issues ranking
  APIs/issues_request/src/controllers/rankingController.js
  APIs/issues_request/src/routes/issueRoute.js
  APIs/issues_request/test/rankingController.js
Labels: Funcionalidade, MDS

#106 Feat#101/pull request ranking
  APIs/pullrequests_request/src/controllers/rankingController.js
  APIs/pullrequests_request/src/routes/pullrequestRoute.js
  APIs/pullrequests_request/test/rankingController.js
Labels: Funcionalidade, MDS

#123 feat(#114): changing requisition endpoint
  APIs/commits_request/src/controllers/commitController.js
  APIs/commits_request/test/commitsRoute.js
Labels: MDS, aprimoramento

#124 Feat#109/update gbd page
  extension/scripts/contentScripts.js
  extension/scripts/screen.js
Labels: Funcionalidade, MDS, aprimoramento

#125 Feat#110/adjust screen size
  extension/scripts/background.js
  extension/scripts/graph.js
  extension/scripts/screen.js
Labels: Funcionalidade, MDS, aprimoramento

#129 Feat#113/expand charts
  extension/manifest.json
  extension/scripts/background.js
  extension/scripts/screen.js
Labels: MDS, aprimoramento

#131 Bug fix#130/fixing oauth and request
  extension/manifest.json
  extension/scripts/background.js
  extension/scripts/contentScripts.js
  extension/scripts/screen.js
Labels: MDS, bug

#132 Develop
  extension/manifest.json
  extension/scripts/background.js
  extension/scripts/contentScripts.js
  extension/scripts/screen.js
Labels: pull request

#136 Feat#119/time config page
  .gitignore
  extension/images/cog-8x.png
  extension/images/logo.jpg
  extension/manifest.json
  extension/popup.html
  extension/scripts/bootstrap.min.js
  extension/scripts/branchesPage.js
  extension/scripts/button.js
  extension/scripts/commitsPage.js
  extension/scripts/graph.js
  extension/scripts/issuesPage.js
  extension/scripts/jquery.min.js
  extension/scripts/observers.js
  extension/scripts/popper.min.js
  extension/scripts/prPage.js
  extension/scripts/screen.js
  extension/scripts/screenConfig.js
  extension/scripts/screenPage.js
  extension/scripts/timeConfigPage.js
  extension/scripts/zenhubRequirements.js
  extension/styles/bootstrap.min.css
  extension/styles/gbdStyle.css
Labels: Funcionalidade, MDS, aprimoramento

#149 Feat#144/update score json
  APIs/ranking_request/src/controllers/rankingController.js
Labels: MDS, aprimoramento

#151 Bug fix#148/fixing bug
  extension/manifest.json
  extension/styles/githubMainPageWebKit.css
  extension/styles/githubWebKit.css
Labels: MDS, Precisa de atenção, bug

#154 Feat#143/ranking page
  extension/manifest.json
  extension/scripts/background.js
  extension/scripts/hashChangeListener.js
  extension/scripts/loadingPage.js
  extension/scripts/metricsCalc.js
  extension/scripts/profilePage.js
  extension/scripts/screenConfig.js
  extension/scripts/screenPage.js
  extension/styles/gbdStyle.css
Labels: Funcionalidade, MDS, aprimoramento

#155 Feat#139/api version
  APIs/branches_request/src/controllers/branchController.js
  APIs/commits_request/src/controllers/commitController.js
  APIs/issues_request/src/controllers/issueController.js
  APIs/issues_request/src/controllers/rankingController.js
  APIs/profile_request/src/controllers/profileController.js
  APIs/pullrequests_request/src/controllers/pullrequestController.js
  APIs/pullrequests_request/src/controllers/rankingController.js
Labels: MDS, aprimoramento

#156 Feat#140/popup personalize
  extension/manifest.json
  extension/popup.html
  extension/popup/popup.html
  extension/scripts/popup.js
  extension/scripts/screenConfig.js
  extension/styles/popupStyle.css
Labels: MDS, aprimoramento

#160 Develop
  APIs/branches_request/src/controllers/branchController.js
  APIs/commits_request/src/controllers/commitController.js
  APIs/issues_request/src/controllers/issueController.js
  APIs/issues_request/src/controllers/rankingController.js
  APIs/profile_request/src/controllers/profileController.js
  APIs/pullrequests_request/src/controllers/pullrequestController.js
  APIs/pullrequests_request/src/controllers/rankingController.js
  README.md
  extension/manifest.json
  extension/popup.html
  extension/popup/popup.html
  extension/scripts/background.js
  extension/scripts/hashChangeListener.js
  extension/scripts/loadingPage.js
  extension/scripts/metricsCalc.js
  extension/scripts/popup.js
  extension/scripts/profilePage.js
  extension/scripts/screenConfig.js
  extension/scripts/screenPage.js
  extension/scripts/settings.js
  extension/styles/gbdStyle.css
  extension/styles/popupStyle.css
Labels: pull request

#162 Feat#115/get date params
  extension/scripts/screenConfig.js
  extension/scripts/screenPage.js
Labels: Funcionalidade, MDS, pendência

#163 Feat#157/improve profile page
  extension/scripts/hashChangeListener.js
  extension/scripts/metricsCalc.js
  extension/scripts/profilePage.js
  extension/scripts/screenConfig.js
  extension/scripts/screenPage.js
  extension/styles/gbdStyle.css
Labels: MDS, aprimoramento

#168 Feat#165/login page
  extension/manifest.json
  extension/scripts/hashChangeListener.js
  extension/scripts/loginPage.js
  extension/scripts/metricsCalc.js
  extension/scripts/profilePage.js
  extension/scripts/screenConfig.js
  extension/scripts/screenPage.js
Labels: MDS, aprimoramento

#177 Feat#146/time based charts
  extension/scripts/commitsPage.js
  extension/scripts/graph.js
  extension/scripts/hashChangeListener.js
  extension/scripts/metricsCalc.js
  extension/scripts/screenConfig.js
  extension/styles/gbdStyle.css
Labels: Funcionalidade, MDS

#178 Bug fix#164/fix config
  extension/scripts/background.js
  extension/scripts/commitsPage.js
  extension/scripts/graph.js
  extension/scripts/hashChangeListener.js
  extension/scripts/metricsCalc.js
  extension/scripts/profilePage.js
  extension/scripts/screenConfig.js
  extension/scripts/screenPage.js
  extension/styles/gbdStyle.css
Labels: MDS, bug
