Repository fga-eps-mds/2019.2-Git-Breakdown, pull requests merged in 2019-10, with the labels that each got.

#70 Feat#65/graph repo url
  extension/manifest.json
  extension/popup.html
  extension/scripts/constants.js
  extension/scripts/graph.js
  extension/scripts/popup.js
Labels: MDS, aprimoramento

#72 Feat#48/git break down tab
  .gitignore
  extension/manifest.json
  extension/scripts/button.js
  extension/scripts/contentScripts.js
Labels: Funcionalidade, MDS

#89 Feat#76/git breakdown screen
  extension/scripts/button.js
Labels: Funcionalidade, aprimoramento, pull request

#88 Feat#79/graph pullrequests
  APIs/pullrequests_request/src/controllers/pullrequestController.js
  extension/manifest.json
  extension/popup.html
  extension/scripts/graph.js
  extension/scripts/popup.js
Labels: Funcionalidade, MDS, aprimoramento

#94 Feat#63/adjust requisition
  APIs/branches_request/src/controllers/branchController.js
  APIs/commits_request/Dockerfile
  APIs/commits_request/bin/server.js
  APIs/commits_request/controllers/commitController.js
  APIs/commits_request/package.json
  APIs/commits_request/src/controllers/commitController.js
  APIs/commits_request/src/routes/commitsRoute.js
  APIs/issues_request/package.json
  APIs/issues_request/src/controllers/issueController.js
  APIs/pullrequests_request/src/controllers/pullrequestController.js
  docker-compose.yml
Labels: MDS, aprimoramento, pull request

#95 Feat#80/graph branches
  .gitignore
  extension/popup.html
  extension/scripts/Chart.min.js
  extension/scripts/graph.js
  extension/scripts/popup.js
Labels: Funcionalidade, MDS

#102 Feat#78/test refactor
  .gitignore
  .gitlab-ci.yml
  APIs/api_gateway/package.json
  APIs/api_gateway/test/index.js
  APIs/branches_request/package.json
  APIs/branches_request/test/branchRoute.js
  APIs/commits_request/package.json
  APIs/commits_request/test/commitsRoute.js
  APIs/issues_request/package.json
  APIs/issues_request/test/issueRoute.js
  APIs/pullrequests_request/package.json
  APIs/pullrequests_request/test/pullrequestRoute.js
Labels: Funcionalidade, MDS

#103 Feat#98/exhibition screen
  extension/manifest.json
  extension/scripts/button.js
  extension/scripts/contentScripts.js
  extension/scripts/popup.js
  extension/scripts/screen.js
Labels: Funcionalidade, MDS, aprimoramento, pull request

#108 feat(#104): refactoring requisitions
  APIs/api_gateway/package.json
  APIs/branches_request/package.json
  APIs/branches_request/src/controllers/branchController.js
  APIs/commits_request/package.json
  APIs/commits_request/src/controllers/commitController.js
  APIs/issues_request/package.json
  APIs/issues_request/src/controllers/issueController.js
  APIs/pullrequests_request/package.json
  APIs/pullrequests_request/src/controllers/pullrequestController.js
Labels: MDS, aprimoramento
